#!/bin/sh
#----------------------------------------------------------------------------
# /etc/ppp/ip-down - called whenever a (i)ppp connection going down
#
# Creation:        10.03.2009
# Last Update:     03.03.09 wrj
#----------------------------------------------------------------------------

# run through ppp start scripts
for i in /etc/ppp/ip-down.d/K??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue
	# start all the specific things
	. $i
done

exit 0
