#!/bin/sh

source /tmp/ulsp/dialout.config
source /tmp/ulsp/dialin.config
source /tmp/ulsp/ipsec.config
source /tmp/ulsp/l2tp.config

CHAP_SECRETS=/etc/ppp/chap-secrets
PAP_SECRETS=/etc/ppp/pap-secrets

user_list=""
pass_list=""

echo "preparing for ppp ..."

mkdir -p /etc/ppp/peers /etc/ppp/chat
rm -f $CHAP_SECRETS $PAP_SECRETS

echo -n > $CHAP_SECRETS

# fill in all users here 
# this reduces dependencies between start scripts significantly

# dialout
if [ $DIALOUT_DEV != "none" ]
then
  ixp=0
  while [ $ixp -lt $DIALOUT_ISP_N ]
  do
    ixp=$(expr $ixp + 1)
    user_list="$user_list $(eval echo '$'$(echo DIALOUT_ISP_${ixp}_USER))"
    pass_list="$pass_list $(eval echo '$'$(echo DIALOUT_ISP_${ixp}_PASS))"
  done
fi

# dialin
if [ $DIALIN_DEV != "none" ]
then
  user_list="$user_list $DIALIN_USER"
  pass_list="$pass_list $DIALIN_PASS"
fi

# l2tp
if [ $IPSEC_GW_L2TP_MODE = "yes" ]
then
  user_list="$user_list $L2TP_CHAP_USER"
  pass_list="$pass_list $L2TP_CHAP_PASS"
fi

# writing chap secrets
while [ "$user_list" ]
do
  set -- $user_list
  user=$1
  shift
  user_list=$@

  set -- $pass_list
  pass=$1
  shift
  pass_list=$@

  # skip if this user/pass is already in chap-secrets files
  if [ -z "$(grep "$user  \*  $pass  \*" $CHAP_SECRETS)" ]
  then
    echo "$user  *  $pass  *" >> $CHAP_SECRETS
  fi
done

chmod go-rwx $CHAP_SECRETS

cp $CHAP_SECRETS $PAP_SECRETS


